---
# Installs new compute nodes in cord-pod XOS configuration using Juju

- name: Include vars
  hosts: all
  tasks:
    - name: Include variables
      include_vars: "{{ item }}"
      with_items:
        - vars/cord_defaults.yml
        - vars/cord.yml
        - vars/example_keystone.yml

- name: Deploy compute nodes
  hosts: head
  vars:
    COMPUTE_HOST_COUNT: "{{ groups['compute'] | length }}"
  roles:
#    - debug
    - vtn-config
