---
- name: Remake all xos system
  hosts: localhost
  connection: local
  vars:
    slack_domain: 'cord-tw.slack.com'
    slack_token: 'T02L2AZ4Q/B41VBBJTH/z13ZVel4QKaeDZAkkU6cz2ni'
    slack_channel: "@breezestars"

  tasks:
    - name: Make components
      make:
        target: "{{ item }}"
        chdir: /home/vagrant/service-profile/cord-pod
      with_items:
        - cleanup
        - local_containers
        - xos
        - vtn
        - fabric
        - cord
        - cord-subscriber

    - name: Notification Task Finished
      slack:
        token: '{{ slack_token }}'
        msg: 'Task Finished'
      delegate_to: localhost
